
spring:
  application:
    name: Employee-Management-System

  data:
    mongodb:
      uri: mongodb+srv://Cluster10305:WmNYYWNrRFxB@cluster10305.8oeti81.mongodb.net/EMS?retryWrites=true&w=majority
      auto-index-creation: true

